<?php $F11 = array(
	array("ACKER Arnaud","F11"),
	array("ANDRIOLO Caroline","F11"),
	array("AYDIN Kadir","F11"),
	array("BALSON Yann","F11"),
	array("BITON Jocelyn","F11"),
	array("CRAGNOLINI Julien","F11"),
	array("ESCHKE Thomas","F11"),
	array("FERNANDES Yoann","F11"),
	array("FREYMANN	Ludwig","F11"),
	array("LASKOWSKI Axel","F11"),
	array("NOYON Nathan","F11"),
	array("PROB	Bastien","F11"),
	array("UBRIG Joric","F11"),
	array("VIRION Louis","F11")
);

$F12 = array(
	array("ANDRIAMIANDRARIVO Hubert Brayan","F12"),
	array("AULEN Lucas","F12"),
	array("BUTTANI Justine","F12"),
	array("DEVEZE Killian","F12"),
	array("DIETSCHIN Valentin","F12"),
	array("GERGES Celine","F12"),
	array("GRIMAZ Jeremie","F12"),
	array("HAAS Mathieu","F12"),
	array("LORANGE Pauline","F12"),
	array("MADER Maxime","F12"),
	array("MATHIEU Tristan","F12"),
	array("MOCK Romain","F12"),
	array("NOIRET-LEMAIRE Lenny","F12"),
	array("ROUX	Anthony","F12"),
	array("SAINT JULIEN Joffrey","F12"),
);

$F13 = array(
	array("BOULAAJOUL Badr","F13"),
	array("FUCHS Emilien","F13"),
	array("GALATI Gaetan","F13"),
	array("HAJNAL Florian","F13"),
	array("ISS Fiona","F13"),
	array("KAYSER Matthieu","F13"),
	array("MAGGAY Cedric","F13"),
	array("ROCHAS Valentin","F13"),
	array("SCHEER-ALM Benjamin Claude","F13"),
	array("SIMON Pierre-Andre","F13"),
	array("VIE Loic","F13"),
	array("WALLISCH Alexis","F13"),
	array("WERLY Tomeline","F13"),
	array("ZIMMER Noe","F13"),
	); 

$F14 = array(
	array("BORGONDO David","F14"),
	array("CLAUDE Leo","F14"),
	array("DE CHENERILLES Pablo","F14"),
	array("FACHE Bruno","F14"),
	array("GAU Pierre-Alain","F14"),
	array("GAWLIK Alexis","F14"),
	array("GOETZ Thibaud","F14"),
	array("HELFER Antoine","F14"),
	array("HOSSANN Vincent","F14"),
	array("LAMARRE Benoit","F14"),
	array("QUENET Raphael","F14"),
	array("SCHNEE Louis","F14"),
	array("VELTZ Quentin","F14"),
	array("VINDIGNI Fabio","F14"),
	array("WILHELM Stephane","F14"),
	);
?>